plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

version = mod_version
group = mod_group_id

base {
    archivesName = archives_base_name
}

repositories {
    mavenLocal()
}

loom {
    mods {
        create(mod_id) {
            sourceSet sourceSets.main
        }
    }
    runs {
        client {
            client()
            ideConfigGenerated true
            name 'Minecraft Client'
        }
        server {
            server()
            ideConfigGenerated true
            name 'Minecraft Server'
            programArgs '--nogui'
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    var replaceProperties = [
            minecraft_version_range: minecraft_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            loader_version_range   : loader_version_range,
            fabric_api_version_range: fabric_api_version_range,
    ]
    inputs.properties replaceProperties

    filesMatching('fabric.mod.json') {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
